package music.model;

public class Song {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.ID
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Artist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String artist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.IDAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer IDAlbum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Album
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String album;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.AlbumArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String albumArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.DiscNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String discNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.TrackNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String trackNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.EpisodeNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String episodeNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SeasonNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String seasonNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Actors
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String actors;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Producer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String producer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SongTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String songTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SongPath
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String songPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Extension
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String extension;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Year
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Genre
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String genre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.FileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer fileLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SongLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer songLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.IDMedia
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer IDMedia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.CacheStatus
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer cacheStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.CacheName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String cacheName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Rating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Bitrate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer bitrate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Seekable
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer seekable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Broadcast
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer broadcast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PreviewState
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer previewState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PreviewName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String previewName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PreviewStartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer previewStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PreviewLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer previewLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Author
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SamplingFrequency
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer samplingFrequency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Stereo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer stereo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.VBR
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer VBR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.BPM
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer BPM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SignType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer signType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SignPart1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer signPart1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SignPart2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer signPart2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SignPart3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer signPart3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SignPart4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer signPart4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PlayCounter
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer playCounter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.LastTimePlayed
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double lastTimePlayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.AudioCDTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer audioCDTrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.FileModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double fileModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.TrackModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double trackModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.MaxSample
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double maxSample;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.NormalizeTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double normalizeTrack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.NormalizeAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double normalizeAlbum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Custom1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String custom1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Custom2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String custom2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Custom3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String custom3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Custom4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String custom4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Custom5
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String custom5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.DateAdded
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double dateAdded;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.OrigFileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer origFileLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PreGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer preGap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PostGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer postGap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.TotalSamples
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer totalSamples;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.PlaybackPos
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer playbackPos;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.StartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.StopTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SkipCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer skipCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.GaplessBytes
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer gaplessBytes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.IDFolder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer IDFolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.IDEpisode
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer IDEpisode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.TrackType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer trackType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.VideoWidth
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer videoWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.VideoHeight
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer videoHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.FrameRate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer frameRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Copyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String copyright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Publisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Encoder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String encoder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Lyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String lyricist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Conductor
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String conductor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Remixer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String remixer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.InvolvedPeople
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String involvedPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.OrigTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String origTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.OrigArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String origArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.OrigLyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String origLyricist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.ParentalRating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String parentalRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.GroupDesc
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String groupDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.SubTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String subTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.ISRC
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String ISRC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.InitialKey
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String initialKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Language
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String language;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebCommercial
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webCommercial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebCopyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webCopyright;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebFilepage
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webFilepage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webArtist;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebSource
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebRadio
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webRadio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebPayment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webPayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebPublisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webPublisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.WebUser
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String webUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.ContainerType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer containerType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.StreamCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer streamCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.StreamInfo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String streamInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.OrigYear
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Integer origYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Tempo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String tempo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Mood
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String mood;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Occasion
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String occasion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Quality
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String quality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Lyrics
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String lyrics;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.Comment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Songs.ArtworkModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    private Double artworkModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.ID
     *
     * @return the value of Songs.ID
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.ID
     *
     * @param ID the value for Songs.ID
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Artist
     *
     * @return the value of Songs.Artist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getArtist() {
        return artist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Artist
     *
     * @param artist the value for Songs.Artist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setArtist(String artist) {
        this.artist = artist == null ? null : artist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.IDAlbum
     *
     * @return the value of Songs.IDAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getIDAlbum() {
        return IDAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.IDAlbum
     *
     * @param IDAlbum the value for Songs.IDAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setIDAlbum(Integer IDAlbum) {
        this.IDAlbum = IDAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Album
     *
     * @return the value of Songs.Album
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Album
     *
     * @param album the value for Songs.Album
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.AlbumArtist
     *
     * @return the value of Songs.AlbumArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getAlbumArtist() {
        return albumArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.AlbumArtist
     *
     * @param albumArtist the value for Songs.AlbumArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setAlbumArtist(String albumArtist) {
        this.albumArtist = albumArtist == null ? null : albumArtist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.DiscNumber
     *
     * @return the value of Songs.DiscNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getDiscNumber() {
        return discNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.DiscNumber
     *
     * @param discNumber the value for Songs.DiscNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setDiscNumber(String discNumber) {
        this.discNumber = discNumber == null ? null : discNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.TrackNumber
     *
     * @return the value of Songs.TrackNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getTrackNumber() {
        return trackNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.TrackNumber
     *
     * @param trackNumber the value for Songs.TrackNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setTrackNumber(String trackNumber) {
        this.trackNumber = trackNumber == null ? null : trackNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.EpisodeNumber
     *
     * @return the value of Songs.EpisodeNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getEpisodeNumber() {
        return episodeNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.EpisodeNumber
     *
     * @param episodeNumber the value for Songs.EpisodeNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setEpisodeNumber(String episodeNumber) {
        this.episodeNumber = episodeNumber == null ? null : episodeNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SeasonNumber
     *
     * @return the value of Songs.SeasonNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getSeasonNumber() {
        return seasonNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SeasonNumber
     *
     * @param seasonNumber the value for Songs.SeasonNumber
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSeasonNumber(String seasonNumber) {
        this.seasonNumber = seasonNumber == null ? null : seasonNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Actors
     *
     * @return the value of Songs.Actors
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getActors() {
        return actors;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Actors
     *
     * @param actors the value for Songs.Actors
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setActors(String actors) {
        this.actors = actors == null ? null : actors.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Producer
     *
     * @return the value of Songs.Producer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getProducer() {
        return producer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Producer
     *
     * @param producer the value for Songs.Producer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setProducer(String producer) {
        this.producer = producer == null ? null : producer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SongTitle
     *
     * @return the value of Songs.SongTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getSongTitle() {
        return songTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SongTitle
     *
     * @param songTitle the value for Songs.SongTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSongTitle(String songTitle) {
        this.songTitle = songTitle == null ? null : songTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SongPath
     *
     * @return the value of Songs.SongPath
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getSongPath() {
        return songPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SongPath
     *
     * @param songPath the value for Songs.SongPath
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSongPath(String songPath) {
        this.songPath = songPath == null ? null : songPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Extension
     *
     * @return the value of Songs.Extension
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Extension
     *
     * @param extension the value for Songs.Extension
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Year
     *
     * @return the value of Songs.Year
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Year
     *
     * @param year the value for Songs.Year
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Genre
     *
     * @return the value of Songs.Genre
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Genre
     *
     * @param genre the value for Songs.Genre
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setGenre(String genre) {
        this.genre = genre == null ? null : genre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.FileLength
     *
     * @return the value of Songs.FileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getFileLength() {
        return fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.FileLength
     *
     * @param fileLength the value for Songs.FileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setFileLength(Integer fileLength) {
        this.fileLength = fileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SongLength
     *
     * @return the value of Songs.SongLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSongLength() {
        return songLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SongLength
     *
     * @param songLength the value for Songs.SongLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSongLength(Integer songLength) {
        this.songLength = songLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.IDMedia
     *
     * @return the value of Songs.IDMedia
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getIDMedia() {
        return IDMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.IDMedia
     *
     * @param IDMedia the value for Songs.IDMedia
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setIDMedia(Integer IDMedia) {
        this.IDMedia = IDMedia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.CacheStatus
     *
     * @return the value of Songs.CacheStatus
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getCacheStatus() {
        return cacheStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.CacheStatus
     *
     * @param cacheStatus the value for Songs.CacheStatus
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCacheStatus(Integer cacheStatus) {
        this.cacheStatus = cacheStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.CacheName
     *
     * @return the value of Songs.CacheName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCacheName() {
        return cacheName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.CacheName
     *
     * @param cacheName the value for Songs.CacheName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCacheName(String cacheName) {
        this.cacheName = cacheName == null ? null : cacheName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Rating
     *
     * @return the value of Songs.Rating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Rating
     *
     * @param rating the value for Songs.Rating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Bitrate
     *
     * @return the value of Songs.Bitrate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getBitrate() {
        return bitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Bitrate
     *
     * @param bitrate the value for Songs.Bitrate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setBitrate(Integer bitrate) {
        this.bitrate = bitrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Seekable
     *
     * @return the value of Songs.Seekable
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSeekable() {
        return seekable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Seekable
     *
     * @param seekable the value for Songs.Seekable
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSeekable(Integer seekable) {
        this.seekable = seekable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Broadcast
     *
     * @return the value of Songs.Broadcast
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getBroadcast() {
        return broadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Broadcast
     *
     * @param broadcast the value for Songs.Broadcast
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setBroadcast(Integer broadcast) {
        this.broadcast = broadcast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PreviewState
     *
     * @return the value of Songs.PreviewState
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPreviewState() {
        return previewState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PreviewState
     *
     * @param previewState the value for Songs.PreviewState
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPreviewState(Integer previewState) {
        this.previewState = previewState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PreviewName
     *
     * @return the value of Songs.PreviewName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getPreviewName() {
        return previewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PreviewName
     *
     * @param previewName the value for Songs.PreviewName
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPreviewName(String previewName) {
        this.previewName = previewName == null ? null : previewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PreviewStartTime
     *
     * @return the value of Songs.PreviewStartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPreviewStartTime() {
        return previewStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PreviewStartTime
     *
     * @param previewStartTime the value for Songs.PreviewStartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPreviewStartTime(Integer previewStartTime) {
        this.previewStartTime = previewStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PreviewLength
     *
     * @return the value of Songs.PreviewLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPreviewLength() {
        return previewLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PreviewLength
     *
     * @param previewLength the value for Songs.PreviewLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPreviewLength(Integer previewLength) {
        this.previewLength = previewLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Author
     *
     * @return the value of Songs.Author
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Author
     *
     * @param author the value for Songs.Author
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SamplingFrequency
     *
     * @return the value of Songs.SamplingFrequency
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSamplingFrequency() {
        return samplingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SamplingFrequency
     *
     * @param samplingFrequency the value for Songs.SamplingFrequency
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSamplingFrequency(Integer samplingFrequency) {
        this.samplingFrequency = samplingFrequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Stereo
     *
     * @return the value of Songs.Stereo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getStereo() {
        return stereo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Stereo
     *
     * @param stereo the value for Songs.Stereo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setStereo(Integer stereo) {
        this.stereo = stereo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.VBR
     *
     * @return the value of Songs.VBR
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getVBR() {
        return VBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.VBR
     *
     * @param VBR the value for Songs.VBR
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setVBR(Integer VBR) {
        this.VBR = VBR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.BPM
     *
     * @return the value of Songs.BPM
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getBPM() {
        return BPM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.BPM
     *
     * @param BPM the value for Songs.BPM
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setBPM(Integer BPM) {
        this.BPM = BPM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SignType
     *
     * @return the value of Songs.SignType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSignType() {
        return signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SignType
     *
     * @param signType the value for Songs.SignType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSignType(Integer signType) {
        this.signType = signType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SignPart1
     *
     * @return the value of Songs.SignPart1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSignPart1() {
        return signPart1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SignPart1
     *
     * @param signPart1 the value for Songs.SignPart1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSignPart1(Integer signPart1) {
        this.signPart1 = signPart1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SignPart2
     *
     * @return the value of Songs.SignPart2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSignPart2() {
        return signPart2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SignPart2
     *
     * @param signPart2 the value for Songs.SignPart2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSignPart2(Integer signPart2) {
        this.signPart2 = signPart2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SignPart3
     *
     * @return the value of Songs.SignPart3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSignPart3() {
        return signPart3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SignPart3
     *
     * @param signPart3 the value for Songs.SignPart3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSignPart3(Integer signPart3) {
        this.signPart3 = signPart3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SignPart4
     *
     * @return the value of Songs.SignPart4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSignPart4() {
        return signPart4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SignPart4
     *
     * @param signPart4 the value for Songs.SignPart4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSignPart4(Integer signPart4) {
        this.signPart4 = signPart4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PlayCounter
     *
     * @return the value of Songs.PlayCounter
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPlayCounter() {
        return playCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PlayCounter
     *
     * @param playCounter the value for Songs.PlayCounter
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPlayCounter(Integer playCounter) {
        this.playCounter = playCounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.LastTimePlayed
     *
     * @return the value of Songs.LastTimePlayed
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getLastTimePlayed() {
        return lastTimePlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.LastTimePlayed
     *
     * @param lastTimePlayed the value for Songs.LastTimePlayed
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setLastTimePlayed(Double lastTimePlayed) {
        this.lastTimePlayed = lastTimePlayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.AudioCDTrack
     *
     * @return the value of Songs.AudioCDTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getAudioCDTrack() {
        return audioCDTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.AudioCDTrack
     *
     * @param audioCDTrack the value for Songs.AudioCDTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setAudioCDTrack(Integer audioCDTrack) {
        this.audioCDTrack = audioCDTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.FileModified
     *
     * @return the value of Songs.FileModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getFileModified() {
        return fileModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.FileModified
     *
     * @param fileModified the value for Songs.FileModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setFileModified(Double fileModified) {
        this.fileModified = fileModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.TrackModified
     *
     * @return the value of Songs.TrackModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getTrackModified() {
        return trackModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.TrackModified
     *
     * @param trackModified the value for Songs.TrackModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setTrackModified(Double trackModified) {
        this.trackModified = trackModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.MaxSample
     *
     * @return the value of Songs.MaxSample
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getMaxSample() {
        return maxSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.MaxSample
     *
     * @param maxSample the value for Songs.MaxSample
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setMaxSample(Double maxSample) {
        this.maxSample = maxSample;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.NormalizeTrack
     *
     * @return the value of Songs.NormalizeTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getNormalizeTrack() {
        return normalizeTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.NormalizeTrack
     *
     * @param normalizeTrack the value for Songs.NormalizeTrack
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setNormalizeTrack(Double normalizeTrack) {
        this.normalizeTrack = normalizeTrack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.NormalizeAlbum
     *
     * @return the value of Songs.NormalizeAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getNormalizeAlbum() {
        return normalizeAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.NormalizeAlbum
     *
     * @param normalizeAlbum the value for Songs.NormalizeAlbum
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setNormalizeAlbum(Double normalizeAlbum) {
        this.normalizeAlbum = normalizeAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Custom1
     *
     * @return the value of Songs.Custom1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCustom1() {
        return custom1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Custom1
     *
     * @param custom1 the value for Songs.Custom1
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCustom1(String custom1) {
        this.custom1 = custom1 == null ? null : custom1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Custom2
     *
     * @return the value of Songs.Custom2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCustom2() {
        return custom2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Custom2
     *
     * @param custom2 the value for Songs.Custom2
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCustom2(String custom2) {
        this.custom2 = custom2 == null ? null : custom2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Custom3
     *
     * @return the value of Songs.Custom3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCustom3() {
        return custom3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Custom3
     *
     * @param custom3 the value for Songs.Custom3
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCustom3(String custom3) {
        this.custom3 = custom3 == null ? null : custom3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Custom4
     *
     * @return the value of Songs.Custom4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCustom4() {
        return custom4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Custom4
     *
     * @param custom4 the value for Songs.Custom4
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCustom4(String custom4) {
        this.custom4 = custom4 == null ? null : custom4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Custom5
     *
     * @return the value of Songs.Custom5
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCustom5() {
        return custom5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Custom5
     *
     * @param custom5 the value for Songs.Custom5
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCustom5(String custom5) {
        this.custom5 = custom5 == null ? null : custom5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.DateAdded
     *
     * @return the value of Songs.DateAdded
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getDateAdded() {
        return dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.DateAdded
     *
     * @param dateAdded the value for Songs.DateAdded
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setDateAdded(Double dateAdded) {
        this.dateAdded = dateAdded;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.OrigFileLength
     *
     * @return the value of Songs.OrigFileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getOrigFileLength() {
        return origFileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.OrigFileLength
     *
     * @param origFileLength the value for Songs.OrigFileLength
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOrigFileLength(Integer origFileLength) {
        this.origFileLength = origFileLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PreGap
     *
     * @return the value of Songs.PreGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPreGap() {
        return preGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PreGap
     *
     * @param preGap the value for Songs.PreGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPreGap(Integer preGap) {
        this.preGap = preGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PostGap
     *
     * @return the value of Songs.PostGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPostGap() {
        return postGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PostGap
     *
     * @param postGap the value for Songs.PostGap
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPostGap(Integer postGap) {
        this.postGap = postGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.TotalSamples
     *
     * @return the value of Songs.TotalSamples
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getTotalSamples() {
        return totalSamples;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.TotalSamples
     *
     * @param totalSamples the value for Songs.TotalSamples
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setTotalSamples(Integer totalSamples) {
        this.totalSamples = totalSamples;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.PlaybackPos
     *
     * @return the value of Songs.PlaybackPos
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getPlaybackPos() {
        return playbackPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.PlaybackPos
     *
     * @param playbackPos the value for Songs.PlaybackPos
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPlaybackPos(Integer playbackPos) {
        this.playbackPos = playbackPos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.StartTime
     *
     * @return the value of Songs.StartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.StartTime
     *
     * @param startTime the value for Songs.StartTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.StopTime
     *
     * @return the value of Songs.StopTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.StopTime
     *
     * @param stopTime the value for Songs.StopTime
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setStopTime(Integer stopTime) {
        this.stopTime = stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SkipCount
     *
     * @return the value of Songs.SkipCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getSkipCount() {
        return skipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SkipCount
     *
     * @param skipCount the value for Songs.SkipCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSkipCount(Integer skipCount) {
        this.skipCount = skipCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.GaplessBytes
     *
     * @return the value of Songs.GaplessBytes
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getGaplessBytes() {
        return gaplessBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.GaplessBytes
     *
     * @param gaplessBytes the value for Songs.GaplessBytes
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setGaplessBytes(Integer gaplessBytes) {
        this.gaplessBytes = gaplessBytes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.IDFolder
     *
     * @return the value of Songs.IDFolder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getIDFolder() {
        return IDFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.IDFolder
     *
     * @param IDFolder the value for Songs.IDFolder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setIDFolder(Integer IDFolder) {
        this.IDFolder = IDFolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.IDEpisode
     *
     * @return the value of Songs.IDEpisode
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getIDEpisode() {
        return IDEpisode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.IDEpisode
     *
     * @param IDEpisode the value for Songs.IDEpisode
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setIDEpisode(Integer IDEpisode) {
        this.IDEpisode = IDEpisode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.TrackType
     *
     * @return the value of Songs.TrackType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getTrackType() {
        return trackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.TrackType
     *
     * @param trackType the value for Songs.TrackType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setTrackType(Integer trackType) {
        this.trackType = trackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.VideoWidth
     *
     * @return the value of Songs.VideoWidth
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getVideoWidth() {
        return videoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.VideoWidth
     *
     * @param videoWidth the value for Songs.VideoWidth
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setVideoWidth(Integer videoWidth) {
        this.videoWidth = videoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.VideoHeight
     *
     * @return the value of Songs.VideoHeight
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getVideoHeight() {
        return videoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.VideoHeight
     *
     * @param videoHeight the value for Songs.VideoHeight
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setVideoHeight(Integer videoHeight) {
        this.videoHeight = videoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.FrameRate
     *
     * @return the value of Songs.FrameRate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getFrameRate() {
        return frameRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.FrameRate
     *
     * @param frameRate the value for Songs.FrameRate
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setFrameRate(Integer frameRate) {
        this.frameRate = frameRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Copyright
     *
     * @return the value of Songs.Copyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Copyright
     *
     * @param copyright the value for Songs.Copyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setCopyright(String copyright) {
        this.copyright = copyright == null ? null : copyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Publisher
     *
     * @return the value of Songs.Publisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Publisher
     *
     * @param publisher the value for Songs.Publisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Encoder
     *
     * @return the value of Songs.Encoder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getEncoder() {
        return encoder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Encoder
     *
     * @param encoder the value for Songs.Encoder
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setEncoder(String encoder) {
        this.encoder = encoder == null ? null : encoder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Lyricist
     *
     * @return the value of Songs.Lyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getLyricist() {
        return lyricist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Lyricist
     *
     * @param lyricist the value for Songs.Lyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setLyricist(String lyricist) {
        this.lyricist = lyricist == null ? null : lyricist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Conductor
     *
     * @return the value of Songs.Conductor
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getConductor() {
        return conductor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Conductor
     *
     * @param conductor the value for Songs.Conductor
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setConductor(String conductor) {
        this.conductor = conductor == null ? null : conductor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Remixer
     *
     * @return the value of Songs.Remixer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getRemixer() {
        return remixer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Remixer
     *
     * @param remixer the value for Songs.Remixer
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setRemixer(String remixer) {
        this.remixer = remixer == null ? null : remixer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.InvolvedPeople
     *
     * @return the value of Songs.InvolvedPeople
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getInvolvedPeople() {
        return involvedPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.InvolvedPeople
     *
     * @param involvedPeople the value for Songs.InvolvedPeople
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setInvolvedPeople(String involvedPeople) {
        this.involvedPeople = involvedPeople == null ? null : involvedPeople.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.OrigTitle
     *
     * @return the value of Songs.OrigTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getOrigTitle() {
        return origTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.OrigTitle
     *
     * @param origTitle the value for Songs.OrigTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOrigTitle(String origTitle) {
        this.origTitle = origTitle == null ? null : origTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.OrigArtist
     *
     * @return the value of Songs.OrigArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getOrigArtist() {
        return origArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.OrigArtist
     *
     * @param origArtist the value for Songs.OrigArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOrigArtist(String origArtist) {
        this.origArtist = origArtist == null ? null : origArtist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.OrigLyricist
     *
     * @return the value of Songs.OrigLyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getOrigLyricist() {
        return origLyricist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.OrigLyricist
     *
     * @param origLyricist the value for Songs.OrigLyricist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOrigLyricist(String origLyricist) {
        this.origLyricist = origLyricist == null ? null : origLyricist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.ParentalRating
     *
     * @return the value of Songs.ParentalRating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getParentalRating() {
        return parentalRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.ParentalRating
     *
     * @param parentalRating the value for Songs.ParentalRating
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setParentalRating(String parentalRating) {
        this.parentalRating = parentalRating == null ? null : parentalRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.GroupDesc
     *
     * @return the value of Songs.GroupDesc
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getGroupDesc() {
        return groupDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.GroupDesc
     *
     * @param groupDesc the value for Songs.GroupDesc
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setGroupDesc(String groupDesc) {
        this.groupDesc = groupDesc == null ? null : groupDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.SubTitle
     *
     * @return the value of Songs.SubTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getSubTitle() {
        return subTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.SubTitle
     *
     * @param subTitle the value for Songs.SubTitle
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setSubTitle(String subTitle) {
        this.subTitle = subTitle == null ? null : subTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.ISRC
     *
     * @return the value of Songs.ISRC
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getISRC() {
        return ISRC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.ISRC
     *
     * @param ISRC the value for Songs.ISRC
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setISRC(String ISRC) {
        this.ISRC = ISRC == null ? null : ISRC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.InitialKey
     *
     * @return the value of Songs.InitialKey
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getInitialKey() {
        return initialKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.InitialKey
     *
     * @param initialKey the value for Songs.InitialKey
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setInitialKey(String initialKey) {
        this.initialKey = initialKey == null ? null : initialKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Language
     *
     * @return the value of Songs.Language
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Language
     *
     * @param language the value for Songs.Language
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebCommercial
     *
     * @return the value of Songs.WebCommercial
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebCommercial() {
        return webCommercial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebCommercial
     *
     * @param webCommercial the value for Songs.WebCommercial
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebCommercial(String webCommercial) {
        this.webCommercial = webCommercial == null ? null : webCommercial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebCopyright
     *
     * @return the value of Songs.WebCopyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebCopyright() {
        return webCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebCopyright
     *
     * @param webCopyright the value for Songs.WebCopyright
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebCopyright(String webCopyright) {
        this.webCopyright = webCopyright == null ? null : webCopyright.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebFilepage
     *
     * @return the value of Songs.WebFilepage
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebFilepage() {
        return webFilepage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebFilepage
     *
     * @param webFilepage the value for Songs.WebFilepage
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebFilepage(String webFilepage) {
        this.webFilepage = webFilepage == null ? null : webFilepage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebArtist
     *
     * @return the value of Songs.WebArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebArtist() {
        return webArtist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebArtist
     *
     * @param webArtist the value for Songs.WebArtist
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebArtist(String webArtist) {
        this.webArtist = webArtist == null ? null : webArtist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebSource
     *
     * @return the value of Songs.WebSource
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebSource() {
        return webSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebSource
     *
     * @param webSource the value for Songs.WebSource
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebSource(String webSource) {
        this.webSource = webSource == null ? null : webSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebRadio
     *
     * @return the value of Songs.WebRadio
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebRadio() {
        return webRadio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebRadio
     *
     * @param webRadio the value for Songs.WebRadio
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebRadio(String webRadio) {
        this.webRadio = webRadio == null ? null : webRadio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebPayment
     *
     * @return the value of Songs.WebPayment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebPayment() {
        return webPayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebPayment
     *
     * @param webPayment the value for Songs.WebPayment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebPayment(String webPayment) {
        this.webPayment = webPayment == null ? null : webPayment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebPublisher
     *
     * @return the value of Songs.WebPublisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebPublisher() {
        return webPublisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebPublisher
     *
     * @param webPublisher the value for Songs.WebPublisher
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebPublisher(String webPublisher) {
        this.webPublisher = webPublisher == null ? null : webPublisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.WebUser
     *
     * @return the value of Songs.WebUser
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getWebUser() {
        return webUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.WebUser
     *
     * @param webUser the value for Songs.WebUser
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setWebUser(String webUser) {
        this.webUser = webUser == null ? null : webUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.ContainerType
     *
     * @return the value of Songs.ContainerType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getContainerType() {
        return containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.ContainerType
     *
     * @param containerType the value for Songs.ContainerType
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setContainerType(Integer containerType) {
        this.containerType = containerType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.StreamCount
     *
     * @return the value of Songs.StreamCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getStreamCount() {
        return streamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.StreamCount
     *
     * @param streamCount the value for Songs.StreamCount
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setStreamCount(Integer streamCount) {
        this.streamCount = streamCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.StreamInfo
     *
     * @return the value of Songs.StreamInfo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getStreamInfo() {
        return streamInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.StreamInfo
     *
     * @param streamInfo the value for Songs.StreamInfo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setStreamInfo(String streamInfo) {
        this.streamInfo = streamInfo == null ? null : streamInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.OrigYear
     *
     * @return the value of Songs.OrigYear
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Integer getOrigYear() {
        return origYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.OrigYear
     *
     * @param origYear the value for Songs.OrigYear
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOrigYear(Integer origYear) {
        this.origYear = origYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Tempo
     *
     * @return the value of Songs.Tempo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getTempo() {
        return tempo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Tempo
     *
     * @param tempo the value for Songs.Tempo
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setTempo(String tempo) {
        this.tempo = tempo == null ? null : tempo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Mood
     *
     * @return the value of Songs.Mood
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getMood() {
        return mood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Mood
     *
     * @param mood the value for Songs.Mood
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setMood(String mood) {
        this.mood = mood == null ? null : mood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Occasion
     *
     * @return the value of Songs.Occasion
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getOccasion() {
        return occasion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Occasion
     *
     * @param occasion the value for Songs.Occasion
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setOccasion(String occasion) {
        this.occasion = occasion == null ? null : occasion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Quality
     *
     * @return the value of Songs.Quality
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getQuality() {
        return quality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Quality
     *
     * @param quality the value for Songs.Quality
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setQuality(String quality) {
        this.quality = quality == null ? null : quality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Lyrics
     *
     * @return the value of Songs.Lyrics
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getLyrics() {
        return lyrics;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Lyrics
     *
     * @param lyrics the value for Songs.Lyrics
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setLyrics(String lyrics) {
        this.lyrics = lyrics == null ? null : lyrics.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.Comment
     *
     * @return the value of Songs.Comment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.Comment
     *
     * @param comment the value for Songs.Comment
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Songs.ArtworkModified
     *
     * @return the value of Songs.ArtworkModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public Double getArtworkModified() {
        return artworkModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Songs.ArtworkModified
     *
     * @param artworkModified the value for Songs.ArtworkModified
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    public void setArtworkModified(Double artworkModified) {
        this.artworkModified = artworkModified;
    }
}