package music.mapper;

import java.util.List;

import music.model.Song;
import music.model.SongExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface SongMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    long countByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int deleteByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int insert(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int insertSelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    List<Song> selectByExample(SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    Song selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int updateByExampleSelective(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int updateByExample(@Param("record") Song record, @Param("example") SongExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int updateByPrimaryKeySelective(Song record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Songs
     *
     * @mbg.generated Sat Mar 23 09:04:41 EDT 2019
     */
    int updateByPrimaryKey(Song record);
}