name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install
      - run: mkdir staging && cp music-api/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          context: .
          push: false
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
